name: Helloworld Docker Build
on: [push]
jobs:
  build-helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses : actions/checkout@v3
      - name : Hello World Docker
        run : | 
          docker build -t helloworld-app .
      - name : Azure Container Registery Login 
        uses: Azure/docker-login@v1
        with:
          login-server: principeavancedocker.azurecr.io
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - run: docker tag helloworld-app principeavancedocker.azurecr.io/helloworld-app
      - run: docker push principeavancedocker.azurecr.io/helloworld-app
