name: Helloworld Docker Build
on: [push]
jobs:
  build-helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses : actions/checkout@v3
      - name : Hello World Docker
        run : | 
          docker build -t helloworld-app .
      - name : Azure scan
        uses: Azure/container-scan@v2
        with:
          image-name: helloworld-app
