name: Helloworld Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-helloworld:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses : actions/checkout@v3
      - name : Hello World Docker
        run : |
          docker build -t helloworld-app .
